language: java
jdk: openjdk8 

cache:
  directories:
    - $HOME/.m2/repository


jobs:
  include:
    - stage: deploy
      name: 'Build & Deploy Jar file'
      script:
      - echo "start build"
      - mvn clean package deploy -DmuleDeploy -Dusername=$username -Dpassword=$password
      if: branch = dev
      